### ISSUE TITLE
Added a new submodule by upstream

### ISSUE THREAD

**Issue by ivan-hc** [bartoszek/AUR-gimp-git#10]
Hi, I don't know more about, but an upstream developer have said that they added a new submodule that causes yuor PKGBUILS have errors. All him said is:
> Until the downstreamers take some action onto PKGBUILD, you can do:
> `git submodule update --init`, before meson, this is enough

on the AUR page many other users have faced the same issue. Can you fix it, please?

I use your PKGBUILD to create an unofficial GIMP-git AppImage, this is one of my latest failed workflows:

https://github.com/ivan-hc/GIMP-appimage/actions/runs/8532275634/job/23373175954

Compiling gimp git starts from this line

https://github.com/ivan-hc/GIMP-appimage/actions/runs/8532275634/job/23373175954#step:3:5419

thank you in advance

**Comment by bartoszek** [comment]
Fixed in bd344ee5adfeae075a2519398d45ce87da945875

**Comment by bartoszek** [comment]
@ivan-hc Could you test something for me: I can't push commits to AUR for a few days now, and posting comments returns error 502. Could you check if it's working on your side?

**Comment by ivan-hc** [comment]
@bartoszek sure, I use your PKGBUILD to built an unofficial AppImage

https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous-git

NOTE: I switched to gimp-develop-git since gimp-git was not updated.

This is the history of my workflow runs on this build

https://github.com/ivan-hc/GIMP-appimage/actions/workflows/GIMP-GIT.yml

A new built is updated daily from your PKGBUILD

**Comment by ivan-hc** [comment]
> @bartoszek sure, I use your PKGBUILD to built an unofficial AppImage
> 
> https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous-git
> 
> NOTE: I switched to gimp-develop-git since gimp-git was not updated.
> 
> This is the history of my workflow runs on this build
> 
> https://github.com/ivan-hc/GIMP-appimage/actions/workflows/GIMP-GIT.yml
> 
> A new build is updated daily from your PKGBUILD

@bartoszek do you prefer I switch to gimp-git again?

**Comment by ivan-hc** [comment]
At the end of this workflow run we will know ig "gimp-git" works again

https://github.com/ivan-hc/GIMP-appimage/actions/runs/8658839950

the process will take about 27+ minutes.

If success, then the new AppImage wil ba available at https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous-git

**Comment by ivan-hc** [comment]
UPDATE: the process is dead after just 2 minutes (new record)

Now I'm trying to install precompiled dependences without ChaoticAUR (so I've not to specify "aur/gimp-git" in YAY)

We will know the truth after this workflow run https://github.com/ivan-hc/GIMP-appimage/actions/runs/8658953284

**Comment by bartoszek** [comment]
> I switched to gimp-develop-git since gimp-git was not updated.

I'm maintaining both `gimp-git` and `gimp-develop-git`  ¯\\\_(ツ)_/¯

**Comment by ivan-hc** [comment]
> > I switched to gimp-develop-git since gimp-git was not updated.
> 
> I'm maintaining both `gimp-git` and `gimp-develop-git` ¯\_(ツ)_/¯ The difference is `develop` in the non-conflicting version, where `gimp-git` replaces `gimp`.

I know that you're the maintainer of both, I've seen that on AUR :smile: 

however in my use case its OK for me, I only had to patch the icons to prevent showing errors about the missing ones (the stable version of gimp is not included in the AppImage).

By reading in the comment, I've seen the pinned one where you said to contact you on github, so I did it
