### ISSUE TITLE
Unneeded pkgver filters

### ISSUE THREAD

**Issue by jonnyrobbie** [bartoszek/AUR-gimp-git#2]
Is it necessary to have all those pkgver rescrictions? Arch does not support partial updates and all of those versions are already in repos, so there should be nobody supported who does not comply. And on the other hand, it screws up with the provides field. For example, I needed to install cairo-git and failed because of this pkgbuild's rescriction and had to manually edit it out.

I propose, remove all the unnecessary and error inducing pkgver filters.

**Comment by bartoszek** [comment]
What _exactly_ is your problem here, I've set up Travis CI to test daily if it builds fine and as for today it reported success
 [![Build Status](https://travis-ci.org/bartoszek/AUR-gimp-develop-git.svg?branch=master)](https://travis-ci.org/bartoszek/AUR-gimp-develop-git)

**Comment by jonnyrobbie** [comment]
> For example, I needed to install cairo-git and failed because of this pkgbuild's rescriction and had to manually edit it out.
 It messes up with the provides field for other packages.

**Comment by bartoszek** [comment]
`depends` array has `cairo>=1.14` which is in `extra` repository [since like 2014](https://github.com/archlinux/svntogit-packages/commit/66775141141f5116e78e9abf5d850b28ac150c15#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a)
Still can't see a problem here.
